config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  post 'gsa_create'=>"welcome#gsa_create"

  root 'welcome#index'
  get 'new'=>"welcome#new"
  get 'generate_csv'=>"welcome#generate_csv"
  get 'clean_price'=>"welcome#clean_price"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
require 'open-uri'
require 'csv'
  def index
	 @tests = Scrape.all.order(id: "DESC").paginate(:page => params[:page], :per_page => 10)

  	# respond_to do |format|
	  #   format.html
	  #   format.csv do
	  #     headers['Content-Disposition'] = "attachment; filename=\"lodging.csv\""
	  #     headers['Content-Type'] ||= 'text/csv'
	  #   end
  	# end
  end

  def new
  	 ScrapWorker.perform_async
  	 redirect_to :back
  end

  def generate_csv
  	@data = Scrape.all
  	headers = ["link","name","rating","street_address","extended_address","city","state","pin","star","price","total_reviews","Traveller_rating","description","amenities","photos","reviews","rooms"] 

  	CSV.open('file.csv', 'w' ) do |writer|
  		writer << headers
  		@data.each do |record|
   			row = [record.link.strip,record.name.strip,record.rating.strip,record.s_address.strip,record.e_address.strip,record.city.strip,record.state.strip,record.pin.strip,record.star.strip,record.price.strip,record.total_reviews.strip,record.traveller_rating,record.description.strip,record.amenities,record.photos,record.reviews,record.rooms]
  			writer <<  row
  			p "--------------------------"
  		end
  	end
  end

  def gsa_new
    
  end

  def gsa_create
    
  end

  def clean_price
    @invalid=[]
    Scrape.all.each do |s|
      if s.price.present?
        if s.price.split('$').length<=1
          @invalid << s.id
        end
      else
         @invalid << s.id
      end
    end
    @scraps = Scrape.where("id IN (?)",@invalid)
    @scraps.update_all(:price=>"n/a")
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_index.html.erb
<h1><%=@name%></h1>
<strong>Street address : </strong><%=@street_address%><br>
<strong>Extended address : </strong><%=@extended_address%><br>
<strong>City :</strong> <%=@city%><br>
<strong>State : </strong><%=@state%><br>
<strong>Pin : </strong><%=@pin%><br>
<strong>Star class : </strong><%=@star_class%><br>
<strong>Hotel Description :</strong><%=@description%>
<br>

<br>
<Strong>Photos :</Strong>

<%if @photos.present? %>
	<%@photos.first(5).each do |p| %>
		<img src="<%=p%>"><br>
	<%end%>
<%end%>

<br><br>
<strong>Amenities : </strong>
<table border="1">
	<thead>
		<tr>
			<th> Amenity Name </th>
		</tr>
	</thead>
	<tbody>
		<% if @amenities.present? %>
			<% @amenities.each do |a| %>
				<tr>
					<td><%=a%></td>
				</tr>
			<%end%>
		<%end%>
	</tbody>
</table> 

<strong>Reviews</strong>
<table border="1">
	<thead>
		<tr>
			<th> By</th>
			<th> Location </th>
			<th> Date</th>
			<th> Title</th>
			<th> Description</th>

		</tr>
	</thead>
	<tbody>
		<% if @reviews.present? %>
			<% @reviews.each do |p| %>
				<tr>
					<td><%=p["by"]%></td>
					<td><%=p["location"]%></td>
					<td><%=p["date"]%></td>
					<td><%=p["title"]%></td>
					<td><%=p["description"]%></td>
				</tr>
			<%end%>
		<%end%>
	</tbody>
</table> 


<!-- 
controller :

def index
		
		url = "http://www.tripadvisor.com/Hotel_Review-g43230-d268394-Reviews-AmericInn_Lodge_Suites_Lake_City-Lake_City_Minnesota.html"
		doc = Nokogiri::HTML(open(url))

		@name = doc.at_css("#HEADING").text
		@street_address= doc.at_css("#HEADING_GROUP .street-address").present? ? doc.at_css("#HEADING_GROUP .street-address").text : "n/a"
		@extended_address= doc.at_css("#HEADING_GROUP .extended-address").present? ? doc.at_css("#HEADING_GROUP .extended-address").text : "n/a"
		@city = doc.at_css('.locality span:nth-child(1)').present? ? doc.at_css('.locality span:nth-child(1)').text : "n/a"
		@state = doc.at_css('.locality span:nth-child(2)').present? ? doc.at_css('.locality span:nth-child(2)').text : "n/a"
		@pin = doc.at_css('.locality span:nth-child(3)').present? ?  doc.at_css('.locality span:nth-child(3)').text : "n/a"
		@star_class = doc.at_css('.stars').present? ? doc.at_css('.stars').text : "n/a"
		@price_range = doc.at_css('.address :nth-child(3) span').present? ? doc.at_css('.address :nth-child(3) span').text : "n/a"
		@description = doc.at_css('.tabs_descriptive_text').present? ? doc.at_css('.tabs_descriptive_text').text : "n/a"
		@photos = []
		# @js = doc.at('script').text
		@js = doc.search("[text()*='lazyImgs']").text.split('lazyImgs = [')[1].split("];")[0]
		parsed_json = ActiveSupport::JSON.decode("["+@js+"]")
		parsed_json.each do |p|
		# 	# p.each do |i|
				@photos<< p["data"]
		# 	# end
		end

		@amenities = []
		doc.css(".property_tags li").each do |item|
			@amenities << item.text.gsub("\n","")
		end
		@reviews=[]
		doc.css("#REVIEWS").each do |review|
			rev={}
			rev["by"]=review.at_css(".mo").text
			rev["location"]=review.at_css(".location").text
			rev["title"] = review.at_css(".quote").text
			rev["date"] = review.at_css(".ratingDate").text
			rev["description"] = review.at_css(".partial_entry").text
			p "-----------------------#{rev.inspect}"
			@reviews << rev
		end

		respond_to do |format|
	    format.html
	    format.csv do
	      headers['Content-Disposition'] = "attachment; filename=\"lodging.csv\""
	      headers['Content-Type'] ||= 'text/csv'
	    end
  	end


  end


 -->











csv.erb file

<%- headers = ["name","street address","extended_address","city","state","pin","star","price","description","amenities","photos","reviews"] -%>
<%= CSV.generate_line headers %>
 <%- headers = [@name.chomp, @street_address.chomp,@extended_address.chomp,@city.chomp,@state.chomp,@pin.chomp,@star_class.chomp,@price_range.chomp,@description.chomp,@amenities.map(&:chomp),@photos.map(&:chomp),@reviews]-%> 
<%= CSV.generate_line(headers).html_safe %>

app/views/welcome/clean_price.html.erb
<table>
	<thead>
		<tr>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%@scraps.each do |s|%>
			<tr>
				<td><%=s.name%></td>
				<td><%=s.price%></td>
				<td><%=s.rooms%></td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/welcome/generate_csv.html.erb
<br><br>Your CSV is ready ,Check in root file with name "file.csv" <br><br>

<%=link_to "Home",root_path%>

app/views/welcome/gsa_new.html.erb
<%=form_for :gsa_form ,url: gsa_create_path do |f|%>

<%end%>

app/views/welcome/index.csv.erb
<%- headers = ["id","name","street address","extended_address","city","state","pin","star","price","description","amenities","photos","reviews"] -%>
<%= CSV.generate_line headers -%>
<%- scrap_data.each do |record|-%>
 	<%- row = [record["name"].chomp,record["street_address"].chomp,record["extended_address"].chomp,record["city"].chomp,record["state"].chomp,record["pin"].chomp,record["star_class"].chomp,record["price_range"].chomp,record["description"].chomp,record["amenities"].map(&:chomp),record["photos"].map(&:chomp),record["reviews"] ] -%> 
	<%= CSV.generate_line(row).html_safe -%>
 <%-end-%>

app/views/welcome/index.html.erb
<%#=render 'index'%>


<%= link_to 'new CSV ', new_path %> <br><br>

<%#= link_to 'Download CSV list', generate_csv_path %>
<%= link_to 'clean price',clean_price_path%>



<br><b><%= @tests.count %> </b>

<table border="1">
	<thead>
	<tr>
		<th>DBid</th>
		<th>name</th>
		<th>rating</th>
		<th>street_address</th>
		<th>extended_address</th>
		<th>city</th>
		<th>state</th>
		<th>pin</th>
		<th>star_class</th>
		<th>price_range</th>
		<th>total_reviews</th>
		<th>traveller_rating</th>
		<!-- <th>description</th> -->
		<!-- <th>amenities</th> -->
		<!-- <th>photos</th> -->
		<!-- <th>reviews</th> -->
		<th>link</th>
		<th>Created at</th>
	</tr>
	</thead>
	<tbody>
		<%@tests.each do |t|%>
		<tr>
			<td><%=t.id %></td>
			<td><%=t.name.strip %></td>
			<td><%=t.rating.strip %></td>
			<td><%=t.s_address.strip %></td>
			<td><%=t.e_address.strip %></td>
			<td><%=t.city.strip %></td>
			<td><%=t.state.strip %></td>
			<td><%=t.pin.strip %></td>
			<td><%=t.star.strip %></td>
			<td><%=t.price.strip %></td>
			<td><%=t.total_reviews.strip %></td>
			<td><%=t.traveller_rating.strip %></td>
			<!-- <td><%=t.description.strip %></td> -->
			<!-- <td><%=t.amenities.strip %></td> -->
			<!-- <td><%=t.photos.strip %></td> -->
			<!-- <td><%=t.reviews.strip %></td> -->
			<td><%=t.link %></td>
			<td><%=t.created_at.strftime('%a, %d %b %Y %H:%M:%S')%></td>
		</tr>
		<%end%>
	</tbody>
</table>



<%= will_paginate @tests %>

app/views/welcome/test.html.erb
yes this is test